### ISSUE TITLE
Improve movement (currently motors run one at a time) 

### ISSUE THREAD

**Issue by IfTrueReturnTrue** [IfTrueReturnTrue/EntitledMHSrobot2021#6]
# How the movement currently works:
Well, for some reason currently the motors run one at a time, which is problematic because first of all it looks bad and also second of all it raises some problems with accuracy and precision. 

#### Potential fixes:
I could make the two pairs of motors each their own **tank**, so I can control them two at a time.

@mykales @BlackReaper665 any other ideas?

**Comment by mykales** [comment]
done
