### ISSUE TITLE
Bot algorithm for whole arena scanning

### ISSUE THREAD

**Issue by IfTrueReturnTrue** [IfTrueReturnTrue/EntitledMHSrobot2021#8]
When the attacking bot doesn't detect a ball in its immediate in front, what should it do next? There should be a loop, or algorithm that the bot repeats

**Requirements**
- simple
- small loop time
- effective

@mykales get thinking

**Comment by mykales** [comment]
try avoid this in total I'd say. **Try** to keep a relative position of the ball and the bot in use of x, y variables (akin to a cartesian plane). It'll be easier to keep the position of the bot in memory, but the ball will be more difficult as it may be knocked by enemy bots which will make it near impossible to track. However, keeping track of the angle the ball is hit by the bot will likely be useful, which can be done by using a push sensor and once again keeping track of the bots movements (and angles).

For what it should do, I'd say we have a few options.
If we are allowed to rotate the bot, then we should rotate to survey the area of 50-100 degrees out in front (depending on position of the bot; if bot is further up near the enemy goal less likely to see ball with 50 degrees then if bot was near friendly goal, so the nearer to the enemy goal the larger area is should survey) If we are not allowed to rotate the bot, try and get the building team to use a motor to rotate only the sensing machines. May be technically difficult or impossible, but just an idea.

If it does not sense anything, than the bot should move back near the goal and do a re-sense of nearly a full 180 degrees. However, if we can achieve communication between the two bots, then this may be unnecessary as the defender bot can be used as also a scout for the other bot when the ball gets on the friendly half.

**Comment by IfTrueReturnTrue** [comment]
hmm ill have a look
